FROM node:20-alpine
WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY .yarnrc.yml .

COPY tsconfig.json .
COPY next.config.mjs .
COPY postcss.config.mjs .
COPY tailwind.config.ts .

RUN corepack enable
RUN yarn set version berry
RUN yarn install --immutable

COPY public ./public
COPY src ./src

CMD yarn dev