FROM node:20-alpine
WORKDIR /app

COPY package.json yarn.lock* ./

COPY tsconfig.json .
COPY next.config.mjs .
COPY postcss.config.mjs .
COPY tailwind.config.ts .

RUN if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
    else echo "Warning: Lockfile not found. It is recommended to commit lockfiles to version control." && yarn install; \
    fi

COPY src ./src
COPY public ./public

CMD yarn dev