services:
  backend:
    container_name: bluebird-backend-dev
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    env_file:
      - .env
  frontend:
    container_name: bluebird-frontend-dev
    image: bluebird-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      # - node_modules:/app/node_modules
    restart: always
    tty: true
    stdin_open: true
# volumes:
#   node_modules:
