services:
  backend:
    container_name: bluebird-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 4000:4000
    env_file:
      - .env

volumes:
  node_modules:
