name: bluebird
services:
  backend:
    container_name: bluebird-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 3030:3030
    env_file:
      - .env
  frontend:
    container_name: bluebird-frontend-prod
    image: bluebird-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    env_file:
      - .env
volumes:
  node_modules:
