name: bluebird
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - supabase_default

  backend:
    container_name: backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      PORT: 4000
    networks:
      - supabase_default

  frontend:
    container_name: frontend-prod
    image: frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      PORT: 3000
      NEXT_PUBLIC_HOST_NAME: ${HOST_NAME}:${HOST_PORT}
    depends_on:
      - backend
    networks:
      - supabase_default

networks:
  supabase_default:
    external: true
