name: bluebird
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - ${HOST_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - supabase_default

  backend:
    container_name: backend-dev
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      PORT: 4000
    networks:
      - supabase_default

  frontend:
    container_name: frontend-dev
    image: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      PORT: 3000
      NEXT_PUBLIC_HOST_NAME: ${HOST_NAME}:${HOST_PORT}
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    restart: always
    tty: true
    stdin_open: true
    depends_on:
      - backend
    networks:
      - supabase_default

volumes:
  node_modules:

networks:
  supabase_default:
    external: true
