// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type Mutation struct {
}

type Query struct {
}

type ShelfCategory struct {
	Ulid string `json:"ulid"`
	Name string `json:"name"`
}

type ShelfFile struct {
	BaseURI string `json:"baseUri"`
	Token   string `json:"token"`
}

type ShelfItem struct {
	Ulid        string         `json:"ulid"`
	Name        string         `json:"name"`
	Category    *ShelfCategory `json:"category"`
	Tags        []*ShelfTag    `json:"tags"`
	Location    *ShelfLocation `json:"location"`
	Description string         `json:"description"`
	Images      []*ShelfFile   `json:"images"`
}

type ShelfLocation struct {
	Ulid string `json:"ulid"`
	Name string `json:"name"`
}

type ShelfTag struct {
	Ulid string `json:"ulid"`
	Name string `json:"name"`
}
